### ISSUE TITLE
Declare initializeNexusStagingRepository task at root project level

### ISSUE THREAD

**Issue by vlsi** [marcphilipp/nexus-publish-plugin#29]
`initializeNexusStagingRepository` is declared in each project.

It results in awkward parallelism: Gradle tries to launch initializeNexusStagingRepository concurrently, however it makes no sense since all of them share the same server url, thus they are just blocked.

Could a single task be created in the root project instead?
It would reduce the number of tasks, and it would make build parallelism more sane.

**Comment by marcphilipp** [comment]
It's probably not the most frequent use case but different subprojects could use different server URLs just like they can use different repositories. Since only a subset of publications might be published, we cannot create all declared staging repos in a single task. Thus I currently don't see an easy way to wire this differently. Do you?

**Comment by vlsi** [comment]
> different subprojects could use different server URLs 

I see.

> Thus I currently don't see an easy way to wire this differently. Do you?

For instance:
1) Create a single task in the root project
2) Make the task use WorkerAPI to create repositories concurrently
3) Make all the sub-projects depend on the main task

> we cannot create all declared staging repos in a single task

Do you mean "it would look a bit awkward" :) ?

**Comment by marcphilipp** [comment]
> Do you mean "it would look a bit awkward" :) ?

That and we don't necessarily need to create all staging repos, e.g. when only the publishing task of one of the subprojects is executed. We could probably inspect the task graph and only create those that we need, though.

**Comment by vlsi** [comment]
>e.g. when only the publishing task of one of the subprojects is executed

Isn't that handled by regular task dependency?

In other words, even current implementation of `nexus-publish-plugin` adds dependency of `publishTasks` on `initializeNexusStagingRepository`.

What's wrong with using the same approach?
I don't see why task graph needs analysis.

**Comment by vlsi** [comment]
> That and we don't necessarily need to create all staging repos

Ok, then a task per repository would do.

**Comment by marcphilipp** [comment]
This plugin is now deprecated in favor of the new [Gradle Nexus Publish Plugin](https://github.com/gradle-nexus/publish-plugin) which provides additional tasks to close and release staging repositories. Please refer to the [migration guide](https://github.com/gradle-nexus/publish-plugin/wiki/Migration-from-gradle_nexus_staging-plugin---nexus_publish-plugin-duo) for details on how to make the switch. If this issue is still relevant to you, please [open a new issue](https://github.com/gradle-nexus/publish-plugin/issues) in the new repository.
