### ISSUE TITLE
Use prefix search to determine staging profile Id

### ISSUE THREAD

**Issue by vlsi** [marcphilipp/nexus-publish-plugin#35]
Use case:
1) Nexus contains staging profile with `name: org.apache.calcite`
2) Project to be deployed has `groupId: org.apache.calcite.avatica` (see Maven project here: https://github.com/apache/calcite-avatica, and it looks like it has no configuration for staging profile group/id)

NPP fails as follows:

```
Execution failed for task ':core:initializeNexusStagingRepository'.
> Failed to find staging profile for package group: org.apache.calcite.avatica
```

It looks like the following chain should use `startsWith` and it should identify the longest prefix out of all matches.

https://github.com/marcphilipp/nexus-publish-plugin/blob/cc61011d31a195b46b48f2bbe14a3d16f54b184a/src/main/kotlin/de/marcphilipp/gradle/nexus/internal/NexusClient.kt#L67-L71

**Comment by szpak** [comment]
@vlsi Have you tried to set [`packageGroup`](https://github.com/marcphilipp/nexus-publish-plugin/blob/master/src/main/kotlin/de/marcphilipp/gradle/nexus/NexusPublishExtension.kt#L39)?

In nexus-publish-plugin directly or in the gradle-nexus-staging-plugin configuration (if you use it) which should be leveraged by nexus-publish-plugin.

**Comment by vlsi** [comment]
@szpak , I know packageGroup is there, however it is kind of unexpected to configure groups here and there.

**Comment by vlsi** [comment]
I see. The same code is present in gradle-nexus-staging-plugin: https://github.com/Codearte/gradle-nexus-staging-plugin/blob/679e4cb67bb0af7050cc6d1fa55e0e7dbeeafc8c/src/main/groovy/io/codearte/gradle/nexus/logic/StagingProfileFetcher.groovy#L19

I guess it might need to be fixed as well.

**Comment by vlsi** [comment]
What I mean is Maven never required me to configure "staging profile group" explicitly, and it enables to push under sub-groups just fine. So I would expect the same (or better) behavior from Gradle plugins.

**Comment by szpak** [comment]
I would say "improved" instead of "fixed" :).

In GNSP the assumption was to use the Gradle project group or `packegeGroup` which has to be exactly matching. Your logic covers some extra case (nice!) which should work unless the same user has access to both `com.example` (all projects in the company/organization) and `com.example.rnd` (only projects from the R&D department) and the project with a group `com.example.rnd.proj1` should be released under `com.example.rnd` (but `com.example` accidentally has higher `id` and is selected by `max()`. Maybe it would be good to throw an exception if more than one matching staging profile id is found?

**Comment by vlsi** [comment]
Thanks for the review. I thought I was using `.name` for comparison.
Now I get Id only after sorting by the prefix length.

**Comment by szpak** [comment]
Great. Feel free to create a PR also in GNSP :).

P.S. The "unit tests" for that could be written in [StagingProfileFetcherSpec](https://github.com/Codearte/gradle-nexus-staging-plugin/blob/679e4cb67bb0af7050cc6d1fa55e0e7dbeeafc8c/src/test/groovy/io/codearte/gradle/nexus/logic/StagingProfileFetcherSpec.groovy) (in GNSP).
