### ISSUE TITLE
Print warning for staging profile id is not provided

### ISSUE THREAD

**Issue by vlsi** [marcphilipp/nexus-publish-plugin#38]
Case: user uses very basic configuration
Problem: NPP requests stagingProfileId which is constant for a given Nexus instance.
Suggestion: print relevant warning (lifecycle level) in case `stagingProfileId` is not defined and the task is trying to fetch one.

Caveat: someone might want to explicitly go with "always query Nexus" approach, so there might be a reason to add "silence the warning" flag.

**Comment by marcphilipp** [comment]
This plugin is now deprecated in favor of the new [Gradle Nexus Publish Plugin](https://github.com/gradle-nexus/publish-plugin) which provides additional tasks to close and release staging repositories. Please refer to the [migration guide](https://github.com/gradle-nexus/publish-plugin/wiki/Migration-from-gradle_nexus_staging-plugin---nexus_publish-plugin-duo) for details on how to make the switch. If this issue is still relevant to you, please [open a new issue](https://github.com/gradle-nexus/publish-plugin/issues) in the new repository.
