### ISSUE TITLE
Kotlin Multiplatform and GitHub matrix

### ISSUE THREAD

**Issue by JavierSegoviaCordoba** [marcphilipp/nexus-publish-plugin#51]
I need to run two machines to publish the macOS artifacts and the Windows artifacts.

The problem is this provokes multiple repositories in Nexus Repository Manager, for example:
```
com.javiersc-1184
com.javiersc-1185
```

How can I avoid this problem? I am using Nexus Staging plugin and I am indicating the exact `stagingProfileId`

**Comment by marcphilipp** [comment]
This plugin is now deprecated in favor of the new [Gradle Nexus Publish Plugin](https://github.com/gradle-nexus/publish-plugin) which provides additional tasks to close and release staging repositories. Please refer to the [migration guide](https://github.com/gradle-nexus/publish-plugin/wiki/Migration-from-gradle_nexus_staging-plugin---nexus_publish-plugin-duo) for details on how to make the switch. If this issue is still relevant to you, please [open a new issue](https://github.com/gradle-nexus/publish-plugin/issues) in the new repository.
