### ISSUE TITLE
staginProfileId not honored

### ISSUE THREAD

**Issue by lamba92** [marcphilipp/nexus-publish-plugin#53]
In project [kotlingram](https://github.com/lamba92/kotlingram/) I am trying to publish a Kotlin/Multipaltform project that needs Windows, MacOs and Linux, and uses GitHub Actions to do so (see [`publication_ci.yml`](https://github.com/lamba92/kotlingram/blob/master/.github/workflows/publication_ci.yml)). 

When executing `gradlew publishToSonatype` the Nexus Publish Plugin do not use the `stagingProfileId` set in root project by the Nexus Staging Plugin (see see root [build.gradle.kts](https://github.com/lamba92/kotlingram/blob/master/build.gradle.kts#L22)) and instead creates a new stagin repository with id `comgithublamba92-{random_number}`. The projects [`:api:core`](https://github.com/lamba92/kotlingram/blob/master/api/core/build.gradle.kts) and [`:api:bot-builder`](https://github.com/lamba92/kotlingram/blob/master/api/bot-builder/build.gradle.kts) apply the Nexus Publish Plugin trough the [`KotlingramPublishedApiPlugin`](https://github.com/lamba92/kotlingram/blob/master/buildSrc/src/main/kotlin/com/github/lamba92/kotlingram/gradle/KotlingramPlugin.kt#L31).

Also the Nexus Staging Repository seems to not honor the repository name when creating one with task `createRepository`, naming the repository with `stagingRepositoryId.set(rootProject.name)` as well.

Probably related to [nexus-staging-plugin/#192](https://github.com/Codearte/gradle-nexus-staging-plugin/issues/192)

**Comment by lamba92** [comment]
Duplicate of #51

**Comment by marcphilipp** [comment]
This plugin is now deprecated in favor of the new [Gradle Nexus Publish Plugin](https://github.com/gradle-nexus/publish-plugin) which provides additional tasks to close and release staging repositories. Please refer to the [migration guide](https://github.com/gradle-nexus/publish-plugin/wiki/Migration-from-gradle_nexus_staging-plugin---nexus_publish-plugin-duo) for details on how to make the switch. If this issue is still relevant to you, please [open a new issue](https://github.com/gradle-nexus/publish-plugin/issues) in the new repository.
