### ISSUE TITLE
Support for original "maven" plugin

### ISSUE THREAD

**Issue by szpak** [marcphilipp/nexus-publish-plugin#8]
Even though `maven-publish` has been (finally) greatly improved this year, some people still use the old [`maven` plugin](https://docs.gradle.org/4.10.2/userguide/maven_plugin.html) to publish their projects (with `uploadArchives`). That plugin suffers the same issue with uploading from Travis as `maven-publish`. Do you plan to add support also for that plugin?

**Comment by marcphilipp** [comment]
TBH I'd rather not support the old `maven` plugin. There's no reason anymore to use it since Gradle 4.8. I think users who'd like to solve the issue with uploading from Travis should consider migrating to `maven-publish` as a prerequisite for using this plugin. That being said, I'll leave this issue open for the time being to see how many people complain. 😉

**Comment by bartoszwalacik** [comment]
@marcphilipp please reconsider adding support for the original `maven` plugin.
The new `maven-publish` plugin dosn't play along with the `signing` plugin. Signing is mandatory when we are publishing to Sonatype Nexus (and then to the Central).

I didn't find the easy way to use `signing` with `maven-publish` without writing complex scripts as described in this post
https://medium.com/@nmauti/sign-and-publish-on-maven-central-a-project-with-the-new-maven-publish-gradle-plugin-22a72a4bfd4b

**Comment by marcphilipp** [comment]
@bartoszwalacik Which Gradle version are you using? The signing plugin supports maven-publish since Gradle 4.8: https://docs.gradle.org/4.8/release-notes.html#signing-publications

**Comment by bartoszwalacik** [comment]
thanks @marcphilipp , I didn't know that

**Comment by marcphilipp** [comment]
This plugin is now deprecated in favor of the new [Gradle Nexus Publish Plugin](https://github.com/gradle-nexus/publish-plugin) which provides additional tasks to close and release staging repositories. Please refer to the [migration guide](https://github.com/gradle-nexus/publish-plugin/wiki/Migration-from-gradle_nexus_staging-plugin---nexus_publish-plugin-duo) for details on how to make the switch. If this issue is still relevant to you, please [open a new issue](https://github.com/gradle-nexus/publish-plugin/issues) in the new repository.
